[project]
name = "blogapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kai", email = "singhshubham43002@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.6",
    "psycopg>=3.3.6",
    "psycopg-binary>=3.3.6",
    "psycopg2-binary>=2.9.13",
    "pydantic-settings>=2.15.0",
    "sqlalchemy[asyncio]>=2.1.1",
    "starlette>=1.7.0",
]

[project.scripts]
blogapp = "blogapp:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
